---
title: "DD regression plots"
output:
  pdf_document:
        includes:
            in_header: header.tex 
---

```{r pre,echo=F,message=F,warning=F}

knitr::opts_chunk$set(warning=F,message=F,echo=F)
require("ggplot2")
require("dplyr")

```

```{r table}

load("DD_model_r_runs.Rdata")

DD.model.list <- list(`rfx vague` = DD_rfx_rs,
                      `rfx informed` = DD_rfx_rsi,
                      `rfx h uniform` = DD_rfx_ru,
                      `rfx h gamma` = DD_rfx_rg,
                      `rfx h taxonomy` = DD_rfx_rh)

tab <- lapply(DD.model.list,function(x)
  data.frame(`$\beta$` = mean(x$BUGSoutput$sims.list$beta),
             `$sd(\beta)$` = sd(x$BUGSoutput$sims.list$beta),
             deviance = mean(x$BUGSoutput$sims.list$deviance),
             pD = x$BUGSoutput$pD,
             DIC = x$BUGSoutput$DIC)
)

tab <- do.call('rbind',tab)
tab$model <- rownames(tab)
tab <- tab[,c(6,1:5)]

knitr::kable(tab,
             row.names=F,
             digits=c(0,3,3,0,0,0),
             align=c('l','r','r','r')) 

```

```{r tax sd, fig.cap="Proportion of variance attributed to each taxonomic level in the analysis."}


sds <- list()
sds[[1]] <- DD_rfx_rs$BUGSoutput$sims.list[grepl('sd',names(DD_rfx_rs$BUGSoutput$sims.list))]
sds[[2]] <- DD_rfx_rsi$BUGSoutput$sims.list[grepl('sd',names(DD_rfx_rsi$BUGSoutput$sims.list))]
sds[[3]] <- DD_rfx_ru$BUGSoutput$sims.list[grepl('sd',names(DD_rfx_ru$BUGSoutput$sims.list))]
sds[[4]] <- DD_rfx_rg$BUGSoutput$sims.list[grepl('sd',names(DD_rfx_rg$BUGSoutput$sims.list))]
sds[[5]] <- DD_rfx_rh$BUGSoutput$sims.list[grepl('sd',names(DD_rfx_rh$BUGSoutput$sims.list)) & !grepl('sigma',names(DD_rfx_rh$BUGSoutput$sims.list))]
#sds[[3]] <- JM$BUGSoutput$sims.list[grepl('sd',names(JM$BUGSoutput$sims.list))]

ssd <- plyr::llply(sds,function(x) apply(as.data.frame(x),1,function(z) z/sum(z)))

msd <- reshape2::melt(ssd)

msd <- msd %>% 
  mutate(Factor = do.call('rbind',strsplit(as.character(Var1),'sd.'))[,2]) %>%
  group_by(L1,Factor) %>%
  summarise(means = median(value),
            q1 = quantile(value,0.025),
            q11 = quantile(value,0.25),
            q33 = quantile(value,0.75),
            q3 = quantile(value,0.975))

msd$Factor <- rep(c('Family','Genus','Order','Population','Species'),5)
msd$L1 <- rep(c('rfx vague','rfx informed','rfx h uniform','rfx h gamma','rfx h taxonomy'),each=5)
colnames(msd)[1] <- 'model'

msd$Factor <- factor(msd$Factor,levels = c('Population','Species','Genus','Family','Order'))
msd$model <- factor(msd$model,levels = rev(c('rfx vague','rfx informed','rfx h uniform','rfx h gamma','rfx h taxonomy')))

dw=0.75
ggplot(msd) + 
  geom_point(aes(x=Factor, y=means, col=model), size=4, position=position_dodge(width=dw)) + 
  geom_linerange(aes(x=Factor, y=means,ymin=q1,ymax=q3,col=model),size=1,position=position_dodge(width=dw)) + 
  geom_linerange(aes(x=Factor, y=means,ymin=q11,ymax=q33,col=model),size=2,position=position_dodge(width=dw)) + 
  theme_classic() + 
  coord_flip() + 
  #ylab(expression(Finite~population~variance~(log[10]~PPMR))) + 
  ylab('Proportion of variance')

```

```{r pred plot prep}

sds <- list()
sds[[1]] <- DD_rfx_rs$BUGSoutput$sims.list[grepl('pred',names(DD_rfx_rs$BUGSoutput$sims.list))]
sds[[2]] <- DD_rfx_rsi$BUGSoutput$sims.list[grepl('pred',names(DD_rfx_rsi$BUGSoutput$sims.list))]
sds[[3]] <- DD_rfx_ru$BUGSoutput$sims.list[grepl('pred',names(DD_rfx_ru$BUGSoutput$sims.list))]
sds[[4]] <- DD_rfx_rg$BUGSoutput$sims.list[grepl('pred',names(DD_rfx_rg$BUGSoutput$sims.list))]
sds[[5]] <- DD_rfx_rh$BUGSoutput$sims.list[grepl('pred',names(DD_rfx_rh$BUGSoutput$sims.list))]
#sds[[3]] <- JM$BUGSoutput$sims.list[grepl('sd',names(JM$BUGSoutput$sims.list))]

msd <- reshape2::melt(sds)

msd <- msd %>% 
  mutate(Factor = L2) %>%
  group_by(L1,Factor,Var2) %>%
  summarise(means = median(value),
            q1 = quantile(value,0.025),
            q11 = quantile(value,0.25),
            q33 = quantile(value,0.75),
            q3 = quantile(value,0.975))

msd$Factor <- rep(rep(c('Family','Genus','Order','Species'),each=50),5)
msd$L1 <- rep(c('rfx vague','rfx informed','rfx h uniform','rfx h gamma','rfx h taxonomy'),each=200)
colnames(msd)[1] <- 'model'

msd$Factor <- factor(msd$Factor,levels = c('Species','Genus','Family','Order'))
msd$model <- factor(msd$model,levels = rev(c('rfx vague','rfx informed','rfx h uniform','rfx h gamma','rfx h taxonomy')))
msd$DD <- log10(DD$EADDC[pred])
msd <- msd %>% group_by(model,Factor) %>% arrange(DD) %>% mutate(Var2 = 1:n())

```
\newpage
\blandscape
```{r predictions, fig.cap="Prediction of degree days to development from taxonomic factors only, at each of four taxonomic levels. At each level, predictions are made under the assuption that the next lower taxonomic level for the species in question was not included in the analysis (e.g., at the family level, we assumed taht the genus for the prediction was not part of the analysis, and the genus mean had to be drawn from the posterior predictive distribution.",fig.width=14,fig.height=9}

dw=5
ggplot(msd) + 
  facet_wrap(Factor~model)+
  geom_point(aes(x=Var2*10, y=means, col=model), size=4, position=position_dodge(width=dw)) + 
  
  geom_linerange(aes(x=Var2*10, y=means,ymin=q1,ymax=q3,col=model),size=1, position=position_dodge(width=dw)) + 
  geom_linerange(aes(x=Var2*10, y=means,ymin=q11,ymax=q33,col=model),size=2, position=position_dodge(width=dw)) + 
  theme_classic()+
  geom_point(aes(x=Var2*10, y=DD), size=4, position=position_dodge(width=dw)) +
  #coord_flip() #+ 
  ylab('Prediction') + 
  xlab('Test point')

```
\elandscape